// <auto-generated />
namespace DataDrivenViewEngine.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateDbForm1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDbForm1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071149086_updateDbForm1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
